version: "3.8"
services:
  keg-herkin:
    privileged: true
    volumes:
      - ${CLI_PATH}:${DOC_CLI_PATH}
      - ${HERKIN_TESTS_ROOT}:${DOC_APP_PATH}/tests
    environment:
      - HERKIN_STEPS_DIR
      - HERKIN_FEATURES_DIR
      - HERKIN_UNIT_DIR
      - HERKIN_WOLF_DIR
      - DOC_APP_PATH
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_PROXY_PORT
      - NODE_ENV
    ports:
      - ${API_PORT}:${API_PORT}
