version: "3.8"
services:
  keg-herkin:
    privileged: true
    volumes:
      - ${CLI_PATH}:${DOC_CLI_PATH}
      - ${KEG_CONTEXT_PATH}/tests/wolf:${DOC_APP_PATH}/tests/wolf
    environment:
      - DOC_APP_PATH
      - DOC_APP_PORT
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - NODE_ENV
    ports:
      - ${API_PORT}:${API_PORT}
