version: "3.8"
services:
  keg-herkin:
    privileged: true
    volumes:
      - ${CLI_PATH}:${DOC_CLI_PATH}
      - ${HERKIN_STEPS_DIR}:${DOC_APP_PATH}/tests/bdd/steps
      - ${HERKIN_FEATURES_DIR}:${DOC_APP_PATH}/tests/bdd/features
      - ${HERKIN_UNIT_DIR}:${DOC_APP_PATH}/tests/unit
      - ${HERKIN_WOLF_DIR}:${DOC_APP_PATH}/tests/wolf
    environment:
      - DOC_APP_PATH
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_PROXY_PORT
      - NODE_ENV
    ports:
      - ${API_PORT}:${API_PORT}
