version: "3.8"
services:
  keg-herkin:
    privileged: true
    volumes:
      - ${CLI_PATH}:${DOC_CLI_PATH}
      - ${KEG_CONTEXT_PATH}/tests/wolf:${DOC_APP_PATH}/tests/wolf
    build:
      context: ${KEG_CONTEXT_PATH}
      dockerfile: ${KEG_DOCKER_FILE}
      args:
        - DOC_APP_PATH
        - DOC_APP_PORT
        - ENV
        - NODE_ENV
        - KEG_BROWSER_WS
        - KEG_BROWSER_TYPE
    container_name: ${CONTAINER_NAME}
    environment:
      - DOC_APP_PATH
      - DOC_APP_PORT
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_NM_INSTALL
      - NODE_ENV
      - KEG_BROWSER_WS
      - KEG_BROWSER_TYPE
    ports:
      - ${API_PORT}:${API_PORT}
