version: "3.8"
networks:
  keg-hub-net:
    external: true
services:
  herkin-backend:
    image: ghcr.io/keg-hub/keg-herkin:develop
    container_name: herkin-backend
    tty: true
    stdin_open: true
    networks:
      - keg-hub-net
    build:
      context: ../
      dockerfile: ./Dockerfile
    ipc: host
    privileged: true
    ports:
      - ${API_PORT}:${API_PORT}
    labels:
      - com.keg.env.context=keg-herkin
      - com.keg.env.api=backend
    environment:
      - API_PORT
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - ENV
      - DISPLAY
      - FIRE_BASE_APP_ID
      - FIRE_BASE_AUTH_DOMAIN
      - FIRE_BASE_KEY
      - FIRE_BASE_MEASURMENT_ID
      - FIRE_BASE_MESSAGING_SENDER_ID
      - FIRE_BASE_PERSISTENCE
      - FIRE_BASE_PROJECT_ID
      - FIRE_BASE_STORAGE_BUCKET
      - FIRE_BASE_TOKEN
      - GITHUB_CLIENT_ID
      - GITHUB_AUTH_USERS
      - HERKIN_API_TYPE=backend
      - HERKIN_APP_URL
      - HERKIN_COOKIE_KEY
      - HERKIN_COOKIE_NAME
      - HERKIN_MOUNT_ROOT
      - HERKIN_USE_VNC=true
      - HERKIN_USE_AUTH=true
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_PROXY_PORT
      - NODE_ENV
      - NO_VNC_PORT
      - SCREENCAST_API_PORT
      - SCREENCAST_PROXY_HOST
      - VNC_PROXY_HOST
      - VNC_SERVER_PORT
      - VNC_VIEW_HEIGHT
      - VNC_VIEW_WIDTH
  herkin-screencast:
    image: ghcr.io/keg-hub/keg-herkin:develop
    container_name: herkin-screencast
    tty: true
    stdin_open: true
    networks:
      - keg-hub-net
    build:
      context: ../
      dockerfile: ./Dockerfile
    ipc: host
    privileged: true
    ports:
      - ${NO_VNC_PORT}:${NO_VNC_PORT}
      - ${SCREENCAST_API_PORT}:${SCREENCAST_API_PORT}
    labels:
      - com.keg.env.context=keg-herkin
      - com.keg.env.api=screencast
    environment:
      - API_PORT
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - ENV
      - DISPLAY
      - FIRE_BASE_APP_ID
      - FIRE_BASE_AUTH_DOMAIN
      - FIRE_BASE_KEY
      - FIRE_BASE_MEASURMENT_ID
      - FIRE_BASE_MESSAGING_SENDER_ID
      - FIRE_BASE_PERSISTENCE
      - FIRE_BASE_PROJECT_ID
      - FIRE_BASE_STORAGE_BUCKET
      - FIRE_BASE_TOKEN
      - GITHUB_CLIENT_ID
      - GITHUB_AUTH_USERS
      - HERKIN_API_TYPE=screencast
      - HERKIN_APP_URL
      - HERKIN_COOKIE_KEY
      - HERKIN_COOKIE_NAME
      - HERKIN_MOUNT_ROOT
      - HERKIN_USE_VNC=true
      - HERKIN_USE_AUTH=true
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_PROXY_PORT
      - NODE_ENV
      - NO_VNC_PORT
      - SCREENCAST_API_PORT
      - SCREENCAST_PROXY_HOST
      - VNC_PROXY_HOST
      - VNC_SERVER_PORT
      - VNC_VIEW_HEIGHT
      - VNC_VIEW_WIDTH



