version: "3.8"
services:
  keg-herkin:
    ipc: host
    privileged: true
    environment:
      - HERKIN_APP_URL
      - HERKIN_ROOT_DIR
      - HERKIN_TESTS_ROOT
      - HERKIN_REPORTS_DIR
      - HERKIN_STEPS_DIR
      - HERKIN_FEATURES_DIR
      - HERKIN_ARTIFACTS_DIR
      - HERKIN_UNIT_DIR
      - HERKIN_SUPPORT_DIR
      - HERKIN_WAYPOINT_DIR
      - HERKIN_PW_SOCKET
      - HERKIN_USE_VNC
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - DISPLAY
      - ENV
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_PROXY_PORT
      - NODE_ENV
      - API_PORT
      - SCREENCAST_API_PORT
      - NO_VNC_PORT
      - VNC_SERVER_PORT
      - VNC_VIEW_HEIGHT
      - VNC_VIEW_WIDTH
      - SCREENCAST_PROXY_HOST
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD

