version: "3.8"
services:
  goblet:
    ipc: host
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    environment:
      - DISPLAY
      - GB_GITHUB_CLIENT_ID
      - GB_GITHUB_AUTH_USERS
      - GB_VNC_ACTIVE=true
      - GB_AUTH_ACTIVE=true
      - GB_NO_VNC_PORT
      - GB_SC_PORT
      - GB_SC_HOST
      - GB_VNC_SERVER_HOST
      - GB_VNC_SERVER_PORT
      - GB_VNC_VIEW_HEIGHT
      - GB_VNC_VIEW_WIDTH
      - GB_BE_PORT
      - DOC_APP_PATH
      - DOC_BUILD_PATH
      - ENV
      - FIRE_BASE_APP_ID
      - FIRE_BASE_AUTH_DOMAIN
      - FIRE_BASE_KEY
      - FIRE_BASE_MEASURMENT_ID
      - FIRE_BASE_MESSAGING_SENDER_ID
      - FIRE_BASE_PERSISTENCE
      - FIRE_BASE_PROJECT_ID
      - FIRE_BASE_STORAGE_BUCKET
      - FIRE_BASE_TOKEN
      - GOBLET_APP_URL
      - GB_BE_COOKIE_KEY
      - GB_BE_COOKIE_NAME
      - GB_SH_MOUNT_ROOT
      - GB_BE_SOCKET_PORT
      - GB_BE_SOCKET_HOST
      - KEG_EXEC_CMD
      - KEG_DOCKER_EXEC
      - KEG_PROXY_HOST
      - KEG_PROXY_PORT
      - NODE_ENV
      - GOBLET_SUB_REPO
    ports:
      - ${GB_BE_PORT}:${GB_BE_PORT}
      - ${GB_NO_VNC_PORT}:${GB_NO_VNC_PORT}
      - ${GB_SC_PORT}:${GB_SC_PORT}

