env:


  # The KEG_CONTEXT_PATH env should be the location of the external app being run
  KEG_CONTEXT_PATH: "{{ process.env.PWD }}"

  # Disable using the trafik proxy, use tap-proxy instead
  KEG_USE_PROXY: true

  KEG_EXEC_CMD: dev

# --- DOCKER IMAGES --- #

  # Root Image to use when building goblet
  KEG_BASE_IMAGE: mcr.microsoft.com/playwright:v1.23.4-focal

  # Name of the image built from the KEG_BASE_IMAGE
  # All sub goblet images are built from this image
  GB_BASE_IMAGE: ghcr.io/gobletqa/goblet-base:develop

  # Development image that contains all the goblet code
  KEG_IMAGE_FROM: ghcr.io/gobletqa/goblet:develop


# --- DOCKER BUILD ENVS --- #
  # Tag / Version of the gitfs docker image to use when building the goblet container
  GB_GITFS_VER: 0.0.0

  # Image/Container Build information
  # IMAGE and CONTAINER_NAME should be the same
  IMAGE: goblet
  CONTAINER_NAME: goblet


# --- DOCKER SYNC ENV CONTEXT --- #

  # Paths within the docker container
  # Used when setting up syncs between host and container
  # Should follow the pattern DOC_<name-of-linked-folder>_PATH
  DOC_APP_PATH: /keg/tap
  DOC_BUILD_PATH: /keg/tap-build
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_PARKIN_PATH: /keg/tap/node_modules/@ltipton/parkin
  DOC_VALUES_PATH: /keg/tap/container
  DOC_BACKEND_PATH: /keg/tap/repos/backend
  DOC_SHARED_PATH: /keg/tap/repos/shared
  DOC_REPOS_PATH: /keg/tap/repos
  DOC_ROOT_PATH: /keg/tap
  DOC_CONTAINER_PATH: /keg/tap/container


# --- SHARED ENVs --- #
  # Required for VNC to work properly
  # Needs a display of some type
  DISPLAY: ":0.0"
  GB_SH_MOUNT_ROOT: /keg/repos
  GB_SH_LOCAL_MOUNT: goblet-local/current
  GB_LOG_LEVEL: 'debug'
  GB_SERVER_ORIGINS: 'localhost,dev.gobletqa.app,gobletqa-develop.local.keghub.io'


# --- BACKEND API ENVs --- #
  GB_BE_API_PORT: 7005
  GB_BE_API_SECURE_PORT: 443
  # Host the FE uses to connect to the BE
  GB_BE_API_HOST: 0.0.0.0
  # Port to forward connections from backend API to screencast
  GB_NO_VNC_PORT: 26369
  # Default to the backend api and host
  # But should be set when running as own server
  GB_BE_SOCKET_PORT: 7005
  GB_BE_SOCKET_HOST: 0.0.0.0
  GB_BE_SOCKR_PATH: '/sockr-socket'

  # --- API JWT AUTH --- #
  GB_BE_JWT_EXP: 7200000
  GB_BE_JWT_SECRET: k3G-H3rkiN-1234
  GB_BE_JWT_CREDENTIALS: true
  GB_BE_JWT_REFRESH_EXP: 7200000
  GB_BE_JWT_REFRESH_SECRET: 4926-G0b13T-g3K

  # --- API COOKIE AUTH --- #
  # GB_BE_COOKIE_SECRET: ""
  GB_BE_COOKIE_SECURE: true
  GB_BE_COOKIE_NAME: goblet
  GB_BE_COOKIE_HTTP_ONLY: true
  GB_BE_COOKIE_OVERWRITE: true
  GB_BE_COOKIE_SAME_SITE: None
  GB_BE_COOKIE_KEY: goblet-cookie-7979


# --- SCREENCAST ENVs --- #
  GB_SC_API_PORT: 7006
  # URL where the screencast is being displayed
  # This is the URL of the server the proxy connects to
  # Update this to call an externally available VNC websocket host
  GB_SC_API_HOST: 0.0.0.0
  # Host of the novnc proxy to tigerVNC
  # This is internal, and generally should not change
  GB_VNC_SERVER_HOST: 0.0.0.0
  GB_VNC_SERVER_PORT: 26370
  GB_VNC_VIEW_HEIGHT: 900
  GB_VNC_VIEW_WIDTH: 1440


# --- CONDUCTOR ENVs --- #
  GB_CD_TIMEOUT: 5000
  GB_CD_SERVER_SECRET: ""
  GB_CD_LOG_LEVEL: info
  GB_CD_PIDS_LIMIT: 500
  GB_CD_PROXY_PORT: 9901
  GB_CD_RATE_LIMIT: 5000
  # Salting the user hash string. Not intended to be secure just anonymous
  GB_CD_HASH_KEY: C0nDuc10R
  # GB_CD_PROXY_HOST: local.keghub.io
  # GB_CD_PROXY_DOMAIN: local.keghub.io


# --- FRONTEND ENVs --- #
  # DEV-ONLY - Default port of the app to expose from the container
  KEG_PROXY_PORT: 19006


  # Define the type of API server to run => all | backend | screencast
  # TODO: @lance-tipton - Add to tasks as an option
  # GOBLET_SUB_REPO: ''

  # TODO: @lance-tipton - Make this more dynamic - value comes from firebase?
  GB_GITHUB_AUTH_USERS: geoffrey.schultz@gmail.com,lancetipton04@gmail.com,nnorman15@gmail.com,lance.tipton@workboard.com,mpcarolin.dev@gmail.com


actions:
  tap:
    build:
      location: /keg/tap
      cmds:
        - yarn build:fe
    install:
      location: /keg/tap
      cmds:
        - yarn setup
    start:
      location: /keg/tap
      cmds:
        - yarn dev
    bundle:
      cmds:
        - node ./tasks/runTask.js deploy build {{ envs.KEG_ACTION_PARAMS }}
    web:
      cmds:
        - yarn web:build
        - rm -rf {{ envs.DOC_BUILD_PATH }}
        - cp -R {{ envs.DOC_CORE_PATH }}/web-build {{ envs.DOC_BUILD_PATH }}
    copy:
      cmds:
        - rm -rf {{ envs.DOC_BUILD_PATH }}
        - cp -R {{ envs.DOC_CORE_PATH }}/web-build {{ envs.DOC_BUILD_PATH }}
    serve:
      cmds:
        - npx serve {{ envs.DOC_BUILD_PATH }} --cors -n -l {{ envs.KEG_PROXY_PORT }}
        - node {{ envs.DOC_APP_PATH }}/repos/backend/index.js
  core:
    install:
      location: /keg/tap/node_modules/keg-core
      cmds:
        - yarn install
  sockr:
    install:
      location: /keg/tap/node_modules/@ltipton/sockr
      cmds:
        - yarn install
    build:
      location: /keg/tap/node_modules/@ltipton/sockr
      cmds:
        - yarn build:rollup
    start:
      location: /keg/tap/node_modules/@ltipton/sockr
      detach: true
      cmds:
        - yarn dev
    att:
      location: /keg/tap/node_modules/@ltipton/sockr
      cmds:
        - bash
  parkin:
    install:
      location: /keg/tap/node_modules/@ltipton/parkin
      cmds:
        - yarn install
    build:
      location: /keg/tap/node_modules/@ltipton/parkin
      cmds:
        - yarn build:rollup
    start:
      location: /keg/tap/node_modules/@ltipton/parkin
      detach: true
      cmds:
        - yarn dev
    att:
      location: /keg/tap/node_modules/@ltipton/parkin
      cmds:
        - bash
  jsutils:
    install:
      location: /keg/tap/node_modules/@keg-hub/jsutils
      cmds:
        - yarn install
    build:
      location: /keg/tap/node_modules/@keg-hub/jsutils
      cmds:
        - yarn build
    start:
      location: /keg/tap/node_modules/@keg-hub/jsutils
      detach: true
      cmds:
        - yarn dev
    copyRoot:
      location: /keg/tap/node_modules/@keg-hub/jsutils
      cmds:
        - rm -rf /keg/tap/node_modules/@keg-hub/jsutils/build
        - cp -R /keg/tap/node_modules/@keg-hub/jsutils/build /keg/tap/node_modules/keg-core/node_modules/@keg-hub/jsutils/build
  retheme:
    att:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
      cmds:
        - bash
    install:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
      cmds:
        - yarn install
    build:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
      cmds:
        - yarn build
    start:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
      detach: true
      cmds:
        - yarn dev
    setup:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
      cmds:
        - yarn install
        - yarn build
  components:
    att:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
      cmds:
        - bash
    install:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
      cmds:
        - yarn install
    build:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
      cmds:
        - yarn build
    start:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
      cmds:
        - yarn dev
    setup:
      location: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
      cmds:
        - yarn install
        - yarn build
