actions:
  tap:
    build:
      cmds:
        - yarn web:build
        - rm -rf {{ envs.DOC_BUILD_PATH }}
        - cp -R {{ envs.DOC_CORE_PATH }}/web-build {{ envs.DOC_BUILD_PATH }}
    serve:
      detached: true
      cmds:
        - npx serve {{ envs.DOC_BUILD_PATH }} --cors -n -l {{ envs.KEG_PROXY_PORT }}
        - node {{ envs.DOC_APP_PATH }}/repos/backend/index.js
env:

  # --- KEG-CLI ENV CONTEXT --- #

  # Set the paths to the linked external app
  # The app should be linked to the keg-cli with `kee`
  # Example command to link the app => `keg tap link kee`
  KEG_DOCKER_FILE: "{{ cli.taps.herkin.path }}/container/Dockerfile"
  KEG_VALUES_FILE: "{{ cli.taps.herkin.path }}/container/values.yml"
  KEG_COMPOSE_DEFAULT: "{{ cli.taps.herkin.path }}/container/docker-compose.yml"
  KEG_COMPOSE_LOCAL: "{{ cli.taps.herkin.path }}/container/docker-compose-local.yml"

  # The KEG_CONTEXT_PATH env should be the location of the external app being run
  KEG_CONTEXT_PATH: "{{ cli.taps.herkin.path }}"

  # Image to use when building herkin
  KEG_BASE_IMAGE: ghcr.io/lancetipton/tap:develop

  # Image to use when running herkin
  # Even if the dockerfile does not use this in the FROM directive
  # It should still be defined as the image used to run the Tap
  KEG_IMAGE_FROM: ghcr.io/lancetipton/keg-herkin:develop

  # This is a true base image from playwright - Alpine Linux are not supported
  # ref: https://playwright.dev/docs/docker/README/#using-on-ci
  # includes node v 14.15.3
  # When building the keg-herkin image, this acts as the parent image
  PLAYWRIGHT_IMAGE_FROM: mcr.microsoft.com/playwright:bionic
  # Since the browsers are downloaded manually
  # Tell yarn install to skip browser download
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

  # --- DOCKER ENV CONTEXT --- #

  # Paths within the docker container
  # Used when setting up syncs between host and container
  # Should follow the pattern DOC_<name-of-linked-folder>_PATH
  DOC_APP_PATH: /keg/tap
  DOC_BUILD_PATH: /keg/tap-build
  DOC_CORE_PATH: /keg/tap/node_modules/keg-core
  DOC_COMPONENTS_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/keg-components
  DOC_RETHEME_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/re-theme
  DOC_RESOLVER_PATH: /keg/tap/node_modules/keg-core/node_modules/@keg-hub/tap-resolver
  DOC_JSUTILS_PATH: /keg/tap/node_modules/@keg-hub/jsutils
  DOC_PARKIN_PATH: /keg/tap/node_modules/@ltipton/parkin
  DOC_SOCKR_PATH: /keg/tap/node_modules/@ltipton/sockr

  EXPO_CLI_VERSION: 4.11.0
  SHARP_CLI_VERSION: 1.15.0
  KEG_NODE_VERSION: 14.17-alpine

  # Default port of the app to expose from the container
  KEG_PROXY_PORT: 19006
  API_PORT: 5005
  SCREENCAST_API_PORT: 5006
  NO_VNC_PORT: 26369
  VNC_SERVER_PORT: 26370
  VNC_VIEW_HEIGHT: 900
  VNC_VIEW_WIDTH: 1440
  # URL where the screencast is being displayed
  # This is the URL of the server the proxy connects to
  # Update this to call an externally available VNC websocket host
  SCREENCAST_PROXY_HOST: 0.0.0.0
  
  # Required for VNC to work properly
  # Needs a display of some type
  DISPLAY: ":0.0"

  # --- GENERAL CONTEXT ENVs --- #
  KEG_EXEC_CMD: dev

  # Image/Container Build information
  # IMAGE and CONTAINER_NAME should be the same
  IMAGE: keg-herkin
  CONTAINER_NAME: keg-herkin
  
  # Git tap url in github
  GIT_APP_URL: https://github.com/lancetipton/keg-herkin.git
  GIT_APP_BRANCH: master
  
  # Browser Local vs VNC envs
  # Defaults to using VNC to display the browser
  HERKIN_USE_VNC: true
  HERKIN_PW_SOCKET: false
